init: fix a linter warning
Fix the following linter warning:

> capability_linux.go:34:8: Error return value is not checked (errcheck)
> 	capget(&hdr, nil)
>	      ^

Here we deliberately ignore the error from capget() since we have no way
to report it, and hdr.ver will be 0 in case of an error anyway.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>